# -- !Ups

-- To ensure UUIDs are autogenerated
create extension if not exists "uuid-ossp";

-- Constraint tables
create table account_status_types (
   name varchar not null constraint pk_account_status_type primary key,
   description varchar not null
);

insert into account_status_types (name, description) values ('EmailVerificationRequired',  'User yet to confirm email');
insert into account_status_types (name, description) values ('UsernameCreationRequired',   'User yet to create username');
insert into account_status_types (name, description) values ('PasswordResetRequired',      'User has to reset password');
insert into account_status_types (name, description) values ('TermsAndConditionsRequired', 'User yet accept terms and conditions');
insert into account_status_types (name, description) values ('LoginReady',                 'User yet to confirm email');

create table users (
   id uuid not null constraint pk_user primary key,
   email varchar not null,
   username varchar,
   first_name varchar,
   last_name varchar,
   photo_url varchar,
   account_status varchar constraint fk_account_type references account_status_types,
   enabled boolean not null default true,
   created_at timestamp not null default now(),
   updated_at timestamp not null default now()
);

create table email_verification_tokens (
    email varchar not null,
    token varchar not null,
    expiry bigint not null,
    primary key (email, token)
);

# -- !Downs