apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-username-lock-cronjob
  namespace: user
spec:
  # This runs every hour, but in production, this should run more frequently
  # Perhaps run every 5-10 mins in production
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clear-username-lock-cronjob
              image: gcr.io/fitcentive-dev-02/gcloud-user-cron-pubsub-image:1.0
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /opt/service-account
                  name: service-account
          restartPolicy: OnFailure
          volumes:
            - name: service-account
              configMap:
                name: user-service-service-account