apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        # Sidecar container for cloudsql-proxy to connect to CloudSql database - recommended approach by Google for GKE
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command:
            - /cloud_sql_proxy
            - -instances=fitcentive-dev-03:northamerica-northeast2:gke-dev-env-cloud-sql-instance:=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
            - name: cloudsql-creds
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: user-service
          image: gcr.io/fitcentive-dev-03/user:1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 300Mi
              cpu: "0.1"
            limits:
              memory: 1000Mi
              cpu: "0.5"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/user/health
              port: 9000
            initialDelaySeconds: 90
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/user/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
          envFrom:
            - secretRef:
                name: internal-service-secret
            - secretRef:
                name: image-service-secret
            - secretRef:
                name: neo4j-secrets
            - secretRef:
                name: user-service-service-account-credentials
            - secretRef:
                name: user-service-cloudsql-database-credentials
          env:
            - name: GCP_PROJECT_NAME
              value: "fitcentive-dev-03"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "5432"
            - name: AUTH_SERVICE_HOST
              value: "http://auth-service.auth"
            - name: AUTH_SERVICE_PORT
              value: "9000"
            - name: SOCIAL_SERVICE_HOST
              value: "http://social-service.social"
            - name: SOCIAL_SERVICE_PORT
              value: "9000"
            - name: DISCOVER_SERVICE_HOST
              value: "http://discover-service.discover"
            - name: DISCOVER_SERVICE_PORT
              value: "9000"
            - name: NOTIFICATION_SERVICE_HOST
              value: "http://notification-service.notification"
            - name: NOTIFICATION_SERVICE_PORT
              value: "9000"
            - name: CHAT_SERVICE_HOST
              value: "http://chat-service.chat"
            - name: CHAT_SERVICE_PORT
              value: "4000"
            - name: DIARY_SERVICE_HOST
              value: "http://diary-service.diary"
            - name: DIARY_SERVICE_PORT
              value: "9000"
            - name: PUBLIC_GATEWAY_SERVICE_HOST
              value: "http://public-gateway-service.public-gateway"
            - name: PUBLIC_GATEWAY_SERVICE_PORT
              value: "9000"
            - name: MEETUP_SERVICE_HOST
              value: "http://meetup-service.meetup"
            - name: MEETUP_SERVICE_PORT
              value: "9000"
            - name: AWARDS_SERVICE_HOST
              value: "http://awards-service.awards"
            - name: AWARDS_SERVICE_PORT
              value: "9000"
            - name: IMAGE_SERVICE_HOST
              value: "http://image-service.image-service"
            - name: IMAGE_SERVICE_PORT
              value: "10260"
            - name: JWT_ISSUER
              value: "https://auth.fitcentive.xyz"
            - name: KEYCLOAK_SERVER_URL
              value: "http://keycloak-service-http.keycloak/auth"
            - name: TOPIC_USER_FOLLOW_REQUESTED
              value: "user-follow-requested"
            - name: TOPIC_USER_FOLLOW_REQUEST_DECISION
              value: "user-follow-request-decision"
            - name: TOPIC_EMAIL_VERIFICATION_TOKEN_CREATED
              value: "email-verification-token-created"
            - name: TOPIC_CLEAR_USERNAME_LOCK_TABLE
              value: "clear-username-lock-table"
            - name: TOPIC_USER_ENABLE_PREMIUM
              value: "user-enable-premium"
            - name: TOPIC_USER_DISABLE_PREMIUM
              value: "user-disable-premium"
            - name: TOPIC_PROMPT_ALL_USERS_WEIGHT_ENTRY
              value: "prompt-all-users-weight-entry"
            - name: TOPIC_PROMPT_USER_TO_LOG_WEIGHT
              value: "prompt-user-to-log-weight"
            - name: SUBSCRIPTION_CLEAR_USERNAME_LOCK_TABLE
              value: "clear-username-lock-table"
            - name: SUBSCRIPTION_USER_ENABLE_PREMIUM
              value: "user-enable-premium"
            - name: SUBSCRIPTION_USER_DISABLE_PREMIUM
              value: "user-disable-premium"
            - name: SUBSCRIPTION_PROMPT_ALL_USERS_WEIGHT_ENTRY
              value: "prompt-all-users-weight-entry"
            - name: RUNTIME_ENVIRONMENT
              value: "gke-dev-env"
            - name: USER_IMAGE_UPLOAD_BUCKET
              value: "fitcentive-dev-03-image-service-upload-images"
            - name: DELETED_USER_STATIC_ID
              value: "aaaaaaaa-aaaa-8bbb-8bbb-aaaaaaaaaaaa"
            - name: DELETED_USER_STATIC_EMAIL
              value: "deleted.user@fitcentive.io"
      volumes:
        - name: cloudsql-creds
          secret:
            secretName: user-service-cloudsql-instance-credentials

